format = """$hostname$directory$git_branch$cmd_duration\
$line_break$character"""

add_newline = false

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[hostname]
ssh_only = true
format = "[$hostname]($style) in "

[directory]
style = "bold bright-blue"

[git_branch]
style = "bold purple"
symbol = ""

[cmd_duration]
format = "took [$duration]($style)"
show_milliseconds = true
style = "yellow"
